https://docs.cocos.com/creator/2.4/manual/zh/components/sprite.html
https://www.google.com
https://github.com/AbelAmerica/iospack
https://github.com/AbelAmerica/iospack/blob/main/goplay-mobile.ipa
https://github.com/AbelAmerica/iospack/blob/main/%E8%AF%B4%E6%98%8E.md
https://github.com/AbelAmerica/iospack/blob/main/manifest.plist
https://www.stackoverflow.com
http://jira.tools5c6ae5402bbe9415.com/secure/Dashboard.jspa
https://admin.goplaystage.com/#/ops/appManagement
https://d4e36d7f03d8b593cb51b02e6b915b51.com/gp-games/slots-app-ios
https://translate.google.com.hk/?hl=hk&sourceid=cnhp&sl=auto&tl=zh-CN&op=translate
https://www.json.cn/#gsc.tab=0
http://jira.tools5c6ae5402bbe9415.com/secure/Dashboard.jspa
https://admin.goplaystage.com/#/ops/ops_siteManagement
https://d4e36d7f03d8b593cb51b02e6b915b51.com/gp-games/newslots-games-cocos/-/issues/service_desk
https://d4e36d7f03d8b593cb51b02e6b915b51.com/gp-games/newslots-games-cocos/-/project_members
https://chatgpt.com/
http://jira.tools5c6ae5402bbe9415.com/secure/RapidBoard.jspa?rapidView=8&projectKey=GOP&view=planning.nodetail&quickFilter=15